app_port: '3000'
pip_install_packages:
  - name: docker
datadog_site: 'datadoghq.com'
datadog_checks:
    http_check:
        init_config:
        instances:
            - name: healthcheck
              url: http://localhost:3000
              timeout: 5
              method: GET
