---

- hosts: webservers
  pre_tasks:
    - name: Update cache
      ansible.builtin.apt:
        upgrade: yes
        update_cache: yes
        cache_valid_time: 86400
  remote_user: root
  roles:
    - geerlingguy.pip
  tasks:
    - name: Start Redmine container
      community.docker.docker_container:
        name: redmine
        auto_remove: yes
        pull: yes
        image: redmine:latest
        ports:
          - "3000:3000"
        env:
          REDMINE_DB_POSTGRES: '{{ db_host }}'
          REDMINE_DB_PORT: '{{ db_port }}'
          REDMINE_DB_DATABASE: '{{ db_name }}'
          REDMINE_DB_USERNAME: '{{ db_username }}'
          REDMINE_DB_PASSWORD: '{{ db_password }}'
